describe cross-device communication, with cited silverpush example
w3ctag/privacy-principles pull request #186
Opened 2022-10-25 22:34 UTC by npdoty

and connected to the threat of cross-device/cross-partition recognition

addresses #71

2022-10-26 16:08 UTC, jyasskin approved these changes

2022-10-26 16:09 UTC, samuelweiler approved these changes

2022-11-04 17:58 UTC, npdoty commented
Re-writes to Identity on the Web section have made this difficult to merge. Cross-device communication and the new text here should be included in describing a common threat to track users across partitions.

2022-11-16 16:35 UTC, darobin requested changes
Small changes, I think this is a good addition.

2022-11-16 16:35 UTC, darobin commented on index.html
> +fingerprinting</a>, or <a>cross-device communication</a>.
```suggestion
fingerprinting</a>, or [=cross-device communication=].
```

2022-11-16 16:35 UTC, darobin commented on index.html
> +client-side code on that device) and a site running on another device. For example, sounds or light
I think that using "site" makes this a bit clunky. Maybe:

```
<dfn>Cross-device communication</dfn> is communication between code on one device and code running on another device.
```

2022-11-30 17:49 UTC, npdoty commented
This now conflicts with the reorganized Identity section. Integrating this text will be easier to do once Identity is organized again, so that it's clear where to insert the technique of cross-device communication as a threat to accomplish cross-partition recognition.

2022-12-14 17:15 UTC, closed without merging