First draft of audiences section
w3ctag/privacy-principles pull request #193
Opened 2022-11-09 07:19 UTC by dmarti

2022-11-15 12:54 UTC, torgo commented on index.html
> + * reviewers of W3C specifications
Maybe we should be clear that it's applicable to all web specifications, not only ones developed at W3C.

2022-11-16 16:30 UTC, darobin requested changes
Most of it is nitpicks because I can't figure out multiline reviews.

2022-11-16 16:30 UTC, darobin commented on index.html
> + * browser developers
```suggestion
 * browser developers,
```

2022-11-16 16:30 UTC, darobin commented on index.html
> + * authors of W3C specifications
```suggestion
 * authors of W3C specifications, and
```

2022-11-16 16:30 UTC, darobin commented on index.html
> + * reviewers of W3C specifications
```suggestion
 * reviewers of W3C specifications.
```

2022-11-16 16:30 UTC, darobin commented on index.html
> +Other audiences include
```suggestion
Other audiences include:
```

2022-11-16 16:30 UTC, darobin commented on index.html
> + * web developers
```suggestion
 * web developers,
```

2022-11-16 16:30 UTC, darobin commented on index.html
> + * policy makers
```suggestion
 * policy makers, and
```

2022-11-16 16:30 UTC, darobin commented on index.html
> + * operators of privacy-related services
```suggestion
 * operators of privacy-related services.
```

2022-11-16 16:30 UTC, darobin commented on index.html
> +cycle of a new Web standard or feature.  Beginning with privacy in mind will help avoid the need to
```suggestion
cycle of a new Web standard or feature, or in the development of Web products.  Beginning with privacy in mind will help avoid the need to 
```

2022-11-16 16:55 UTC, jyasskin commented on index.html
> + * reviewers of W3C specifications
To reduce the extra whitespace:
```suggestion
 * browser developers
 * authors of W3C specifications
 * reviewers of W3C specifications
```

2022-11-16 16:55 UTC, jyasskin commented on index.html
> +cycle of a new Web standard or feature.  Beginning with privacy in mind will help avoid the need to
Or just
```suggestion
cycle of a new feature.  Beginning with privacy in mind will help avoid the need to 
```

2022-11-16 17:12 UTC, dmarti commented on index.html
> + * web developers
I will move web developers to primary audiences.

2022-11-16 23:51 UTC, dmarti commented
All comments on this one fixed, at least 1 approving review is required to merge this pull request. Can merge then.  @darobin @jyasskin @torgo

2022-11-16 23:53 UTC, jyasskin approved these changes

2022-11-17 00:11 UTC, merged