users -> people
w3ctag/privacy-principles pull request #69
Opened 2021-10-20 19:06 UTC by torgo

this is an experimental PR to demonstrate what it might look like to change "users" to "people" across thd document. 

Referencing #52

***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/69.html" title="Last updated on Nov 3, 2021, 2:49 PM UTC (5b75327)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/69/9cc8254...5b75327.html" title="Last updated on Nov 3, 2021, 2:49 PM UTC (5b75327)">Diff</a>

2021-11-02 18:48 UTC, wseltzer approved these changes
LGTM

2021-11-02 22:05 UTC, darobin requested changes
I think the two remaining comments are cases where keeping `user` would be a lot better. After that, it's all good!

2021-11-02 22:05 UTC, darobin commented on index.html
> +[=identity=] to multiple [=sites=] that people understand represent a single [=party=], or to a
I still think that `user` is better in this context.

2021-11-02 22:05 UTC, darobin commented on index.html
> +For example, a site that sends SMS without someone's intent could cause them to
Same. I still think that `user` is better in this context.

2021-11-02 22:05 UTC, darobin commented on index.html
> +For example, a site that sends SMS without someone's intent could cause them to
```suggestion
For example, a site that sends SMS without the user's intent could cause them to
```

2021-11-02 22:05 UTC, darobin commented on index.html
> +[=identity=] to multiple [=sites=] that people understand represent a single [=party=], or to a
```suggestion
[=identity=] to multiple [=sites=] that the user understands represent a single [=party=], or to a
```

2021-11-03 15:28 UTC, darobin approved these changes

2021-11-03 15:33 UTC, merged